// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5tthOy-UwB0Ri8e0YnHnvyBsJBdmvgOc',
    appId: '1:796755420420:web:dda120072cce1166371c51',
    messagingSenderId: '796755420420',
    projectId: 'pet-tracker-916eb',
    authDomain: 'pet-tracker-916eb.firebaseapp.com',
    storageBucket: 'pet-tracker-916eb.appspot.com',
    measurementId: 'G-R2Z5GR0J9Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPSpt-oWVOYg4tAF5vI1d2enX2azfgtSw',
    appId: '1:796755420420:android:cbbac0b59bc4f380371c51',
    messagingSenderId: '796755420420',
    projectId: 'pet-tracker-916eb',
    storageBucket: 'pet-tracker-916eb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCg4U5Kmzx2x3UXjpDFtgLg-apXRA8QBRo',
    appId: '1:796755420420:ios:2aafb18d5a6f506a371c51',
    messagingSenderId: '796755420420',
    projectId: 'pet-tracker-916eb',
    storageBucket: 'pet-tracker-916eb.appspot.com',
    iosClientId: '796755420420-q5ocekbeq9fo9qtoj7bt1jmfhja5b20i.apps.googleusercontent.com',
    iosBundleId: 'com.example.petTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCg4U5Kmzx2x3UXjpDFtgLg-apXRA8QBRo',
    appId: '1:796755420420:ios:2aafb18d5a6f506a371c51',
    messagingSenderId: '796755420420',
    projectId: 'pet-tracker-916eb',
    storageBucket: 'pet-tracker-916eb.appspot.com',
    iosClientId: '796755420420-q5ocekbeq9fo9qtoj7bt1jmfhja5b20i.apps.googleusercontent.com',
    iosBundleId: 'com.example.petTracker',
  );
}
